Main(WScript.Arguments);

function Main(args)
{
	if (args.Length != 2)
		Usage();

	var version = args.Item(0);
	var oem = args.Item(1);

	WScript.Echo("/*");
	WScript.Echo(" * WARNING:  This file is automatically generated.");
	WScript.Echo(" *           Do not hand edit this file.");
	WScript.Echo(" */");
	WScript.Echo("");

	while (!WScript.StdIn.AtEndOfStream) {
		var line = WScript.StdIn.ReadLine();
		line = line.replace("@@VERSION_STRING@@", '"' + version + '"');
		line = line.replace("@@OEM_NAME@@", '"' + oem + '"');
		WScript.Echo(line);
	}
}

function Usage()
{
	WScript.StdErr.WriteLine("Usage: " + WScript.ScriptName +
	    " <version string> <oem name>");
	WScript.Exit(1);
}
