all:
	msbuild $(SUL)\BlueStacksTV\Dotnet\BlueStacksTV\BlueStacksTV\BlueStacksTV.csproj /p:Configuration=Release

clean:
	del /f $(SUL)\BlueStacksTV\Dotnet\BlueStacksTV.exe
	del /f $(SUL)\BlueStacksTV\Dotnet\BlueStacksTV.pdb
