DLL = JSON
SRCS = \
    Core@CodeTitans\IStringReader.cs \
    Core@CodeTitans\NumericHelper.cs \
    Core@CodeTitans\SerializationHelper.cs \
    Core@CodeTitans\StringHelper.cs \
    JSON@CodeTitans\IJSonObject.cs \
    JSON@CodeTitans\IJSonReader.cs \
    JSON@CodeTitans\IJSonSerializable.cs \
    JSON@CodeTitans\IJSonWriter.cs \
    JSON@CodeTitans\IJSonWriterArrayItem.cs \
    JSON@CodeTitans\IJSonWriterItem.cs \
    JSON@CodeTitans\IJSonWriterObjectItem.cs \
    JSON@CodeTitans\JSonException.cs \
    JSON@CodeTitans\JSonIgnoreAttribute.cs \
    JSON@CodeTitans\JSonMemberAttribute.cs \
    JSON@CodeTitans\JSonMemberMissingException.cs \
    JSON@CodeTitans\JSonReader.cs \
    JSON@CodeTitans\JSonReaderException.cs \
    JSON@CodeTitans\JSonReaderTokenInfo.cs \
    JSON@CodeTitans\JSonReaderTokenType.cs \
    JSON@CodeTitans\JSonSerializableAttribute.cs \
    JSON@CodeTitans\JSonWriter.cs \
    JSON@CodeTitans\JSonWriterException.cs \
    JSON@CodeTitans\JSonWriterTokenInfo.cs \
    JSON@CodeTitans\JSonWriterTokenType.cs \
    JSON@CodeTitans\Objects\JSonArray.cs \
    JSON@CodeTitans\Objects\JSonBooleanObject.cs \
    JSON@CodeTitans\Objects\JSonDecimalObject.cs \
    JSON@CodeTitans\Objects\JSonDictionary.cs \
    JSON@CodeTitans\Objects\JSonObjectConverter.cs \
    JSON@CodeTitans\Objects\JSonStringObject.cs \
    JSON@CodeTitans\ReaderHelpers\FclObjectFactory.cs \
    JSON@CodeTitans\ReaderHelpers\IObjectFactory.cs \
    JSON@CodeTitans\ReaderHelpers\JSonObjectFactory.cs \
    JSON@CodeTitans\ReaderHelpers\TokenData.cs \
    JSON@CodeTitans\ReaderHelpers\TokenDataChar.cs \
    JSON@CodeTitans\ReaderHelpers\TokenDataString.cs \
    JSON@CodeTitans\WriterHelpers\ArrayWriter.cs \
    JSON@CodeTitans\WriterHelpers\ObjectWriter.cs \
    AssemblyInfo.cs

CSFLAGS = $(CSFLAGS) /debug:full
!INCLUDE $(M)\win_csharp_dll.mk
