PROG = HD-CloudPost

JSON_SOURCE_FILES = \
       $(C)\JSON\Core@CodeTitans\IStringReader.cs \
       $(C)\JSON\Core@CodeTitans\NumericHelper.cs \
       $(C)\JSON\Core@CodeTitans\SerializationHelper.cs \
       $(C)\JSON\Core@CodeTitans\StringHelper.cs \
       $(C)\JSON\JSON@CodeTitans\IJSonObject.cs \
       $(C)\JSON\JSON@CodeTitans\IJSonReader.cs \
       $(C)\JSON\JSON@CodeTitans\IJSonSerializable.cs \
       $(C)\JSON\JSON@CodeTitans\IJSonWriter.cs \
       $(C)\JSON\JSON@CodeTitans\IJSonWriterArrayItem.cs \
       $(C)\JSON\JSON@CodeTitans\IJSonWriterItem.cs \
       $(C)\JSON\JSON@CodeTitans\IJSonWriterObjectItem.cs \
       $(C)\JSON\JSON@CodeTitans\JSonException.cs \
       $(C)\JSON\JSON@CodeTitans\JSonIgnoreAttribute.cs \
       $(C)\JSON\JSON@CodeTitans\JSonMemberAttribute.cs \
       $(C)\JSON\JSON@CodeTitans\JSonMemberMissingException.cs \
       $(C)\JSON\JSON@CodeTitans\JSonReader.cs \
       $(C)\JSON\JSON@CodeTitans\JSonReaderException.cs \
       $(C)\JSON\JSON@CodeTitans\JSonReaderTokenInfo.cs \
       $(C)\JSON\JSON@CodeTitans\JSonReaderTokenType.cs \
       $(C)\JSON\JSON@CodeTitans\JSonSerializableAttribute.cs \
       $(C)\JSON\JSON@CodeTitans\JSonWriter.cs \
       $(C)\JSON\JSON@CodeTitans\JSonWriterException.cs \
       $(C)\JSON\JSON@CodeTitans\JSonWriterTokenInfo.cs \
       $(C)\JSON\JSON@CodeTitans\JSonWriterTokenType.cs \
       $(C)\JSON\JSON@CodeTitans\Objects\JSonArray.cs \
       $(C)\JSON\JSON@CodeTitans\Objects\JSonBooleanObject.cs \
       $(C)\JSON\JSON@CodeTitans\Objects\JSonDecimalObject.cs \
       $(C)\JSON\JSON@CodeTitans\Objects\JSonDictionary.cs \
       $(C)\JSON\JSON@CodeTitans\Objects\JSonObjectConverter.cs \
       $(C)\JSON\JSON@CodeTitans\Objects\JSonStringObject.cs \
       $(C)\JSON\JSON@CodeTitans\ReaderHelpers\FclObjectFactory.cs \
       $(C)\JSON\JSON@CodeTitans\ReaderHelpers\IObjectFactory.cs \
       $(C)\JSON\JSON@CodeTitans\ReaderHelpers\JSonObjectFactory.cs \
       $(C)\JSON\JSON@CodeTitans\ReaderHelpers\TokenData.cs \
       $(C)\JSON\JSON@CodeTitans\ReaderHelpers\TokenDataChar.cs \
       $(C)\JSON\JSON@CodeTitans\ReaderHelpers\TokenDataString.cs \
       $(C)\JSON\JSON@CodeTitans\WriterHelpers\ArrayWriter.cs \
       $(C)\JSON\JSON@CodeTitans\WriterHelpers\ObjectWriter.cs \


SRCS = \
       $(JSON_SOURCE_FILES) \
       $(SUL)\Common\DotNet\Logger.cs \
       $(SUL)\Version.cs \
       CloudPost.cs \
       AssemblyInfo.cs \

!INCLUDE $(M)\win_utils.mk

CSFLAGS = $(CSFLAGS) /debug:full
CSFLAGS = $(CSFLAGS) /platform:x86
CSFLAGS = $(CSFLAGS) /target:winexe

all: $(PROG).exe

clean:
	del 7zSDcfg.txt $(PROG).exe $(PROG).7z $(PROG)_native.exe $(PROG).7z.exe $(PROG).pdb
	del /Q *.exe
	del /Q *.pdb

!INCLUDE $(M)\win_csharp.mk
