DEPLOYTOOLINSTALLER = $(SUL)Tool\DeployTool\Dotnet\HD-DeployTool_KK_$(FLAVOR).exe
DEPLOYTOOLUNINSTALLER = $(SUL)Tool\DeployTool\Uninstaller\Dotnet\HD-DeployTool_Uninstaller.exe

!IFDEF QEMU3BT
COEXISTENCE_BIT = ENABLE_COEXISTENCE_BIT
!ELSE
COEXISTENCE_BIT = DISABLE_COEXISTENCE_BIT
!ENDIF

deploytool:
	CMD /C "$(MAKE) /$(MAKEFLAGS) $(DEPLOYTOOLINSTALLER)"
	CMD /C "$(MAKE) /$(MAKEFLAGS) $(DEPLOYTOOLUNINSTALLER)"
	CMD /C "CD $(SUL)"

$(DEPLOYTOOLINSTALLER): force
	CMD /C "CD $(SUL)Tool\DeployTool\Uninstaller\DotNet & $(MAKE) /$(MAKEFLAGS) clean"
	CMD /C "CD $(SUL)Tool\DeployTool\DotNet & $(MAKE) /$(MAKEFLAGS) clean all COEXISTENCE_BIT=$(COEXISTENCE_BIT)"
!IFDEF SIGN_PACKAGE
!IFDEF USE_SHA2_SIGNING
	$(SIGNTOOL) sign /s "my" /ac $(S)\Certs\MSCV-VSClass3.cer /sha1 "F1AECC2B5B251589B4B4009D30201AC01ABBA7DC" /n "BlueStack Systems, Inc." /t "http://timestamp.verisign.com/scripts/timestamp.dll" /d "BlueStacks App Player" $(DEPLOYTOOLINSTALLER)
!ELSE
	$(SIGNTOOL) sign /s "my" /ac $(S)\Certs\MSCV-VSClass3.cer /a /n "BlueStack Systems, Inc." /t "http://timestamp.verisign.com/scripts/timestamp.dll" /d "BlueStacks App Player" $(DEPLOYTOOLINSTALLER)
!ENDIF
!ENDIF

$(DEPLOYTOOLUNINSTALLER): force
	CMD /C "CD $(SUL)Tool\DeployTool\Uninstaller\DotNet & $(MAKE) /$(MAKEFLAGS) clean all"
!IFDEF SIGN_PACKAGE
!IFDEF USE_SHA2_SIGNING
	$(SIGNTOOL) sign /s "my" /ac $(S)\Certs\MSCV-VSClass3.cer /sha1 "F1AECC2B5B251589B4B4009D30201AC01ABBA7DC" /n "BlueStack Systems, Inc." /t "http://timestamp.verisign.com/scripts/timestamp.dll" /d "BlueStacks App Player" $(DEPLOYTOOLUNINSTALLER)
!ELSE
	$(SIGNTOOL) sign /s "my" /ac $(S)\Certs\MSCV-VSClass3.cer /a /n "BlueStack Systems, Inc." /t "http://timestamp.verisign.com/scripts/timestamp.dll" /d "BlueStacks App Player" $(DEPLOYTOOLUNINSTALLER)
!ENDIF
!ENDIF

force:
