# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0002_qq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmulatorActivity',
        ),
        migrations.DeleteModel(
            name='EmulatorInstall',
        ),
        migrations.DeleteModel(
            name='EngineActivity',
        ),
        migrations.DeleteModel(
            name='EngineInstall',
        ),
        migrations.DeleteModel(
            name='QQ',
        ),
    ]
