# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datastats', '0003_auto_20160531_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('datetime', models.DateTimeField(verbose_name='\u6570\u636e\u63d2\u5165\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmulatorInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('datetime', models.DateTimeField(verbose_name='\u6570\u636e\u63d2\u5165\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('datetime', models.DateTimeField(verbose_name='\u6570\u636e\u63d2\u5165\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('datetime', models.DateTimeField(verbose_name='\u6570\u636e\u63d2\u5165\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('datetime', models.DateTimeField(verbose_name='\u6570\u636e\u63d2\u5165\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
