# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0004_emulatoractivity_emulatorinstall_engineactivity_engineinstall_qq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QQ',
        ),
    ]
