# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0006_resultemulatoractivity_resultemulatorinstall_resultengineactivity_resultengineinstall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultemulatoractivity',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultemulatoractivity',
            name='dst_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultemulatorinstall',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultemulatorinstall',
            name='dst_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultengineactivity',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultengineactivity',
            name='dst_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultengineinstall',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultengineinstall',
            name='dst_count',
            field=models.IntegerField(default=0),
        ),
    ]
