# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-12 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0010_resultappactivity_resultappinstall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultAppInstall',
            new_name='AppActivity',
        ),
        migrations.RenameModel(
            old_name='ResultAppActivity',
            new_name='AppInstall',
        ),
    ]
