# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0013_auto_20160613_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultemulatorsession',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
