# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0015_appcenterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAppActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('dst_count', models.IntegerField(default=0)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('package_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultAppInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('dst_count', models.IntegerField(default=0)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('package_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
