# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0016_resultappactivity_resultappinstall'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultappactivity',
            name='game_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultappinstall',
            name='game_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultappactivity',
            name='package_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultappinstall',
            name='package_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
