# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0017_auto_20160615_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultappinstall',
            name='game_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
