# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0020_midresultinstallinit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midresultinstallinit',
            old_name='count',
            new_name='dst_count',
        ),
    ]
