# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0025_resultgeneralapkinsterror_resultgeneralengineinstall_resultgeneralengineinsterror_resultgeneralengin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultGeneralAPKInstError',
        ),
        migrations.DeleteModel(
            name='ResultGeneralEngineInstall',
        ),
        migrations.DeleteModel(
            name='ResultGeneralEngineInstError',
        ),
        migrations.DeleteModel(
            name='ResultGeneralEngInitError',
        ),
        migrations.DeleteModel(
            name='ResultGeneralOsVersion',
        ),
    ]
