# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0028_resultemulatordownload'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resultemulatordownload',
            table='result_emulator_download',
        ),
    ]
