# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0036_resultusercomputerinfocpu_resultusercomputerinfomemory_resultusercomputerinfoos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=16, unique=True)),
                ('info', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
