# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0039_resultapptotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultapptotal',
            name='version',
            field=models.CharField(default='', max_length=32),
        ),
    ]
