# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0040_resultapptotal_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultGeneralUninstallReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100)),
                ('op', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('uninst_reason_string', models.CharField(blank=True, default='', max_length=512)),
                ('uninst_reason_dword', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(verbose_name='GeneralData uptime\u5b57\u6bb5')),
            ],
            options={
                'db_table': 'result_general_uninstall_reason',
            },
        ),
    ]
