# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0041_resultgeneraluninstallreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldata',
            name='json',
            field=models.TextField(help_text='json\u6570\u636e', max_length=1024),
        ),
    ]
