# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0043_auto_20160721_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfUninstallReasonMeaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, unique=True)),
                ('meaning', models.CharField(max_length=64)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'conf_uninstall_reason_meaning',
            },
        ),
    ]
