# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0047_auto_20160726_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultappactivity',
            name='channel',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resultappinstall',
            name='channel',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resultemulatoractivity',
            name='channel',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resultemulatorinstall',
            name='channel',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resultengineactivity',
            name='channel',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resultengineinstall',
            name='channel',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
