# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0048_auto_20160726_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultemulatorinstallcount',
            name='channel',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
