# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0051_auto_20160727_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midresultinstallinitemulator',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='midresultinstallinitengine',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultappactivity',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultappinstall',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultemulatoractivity',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultemulatorinstall',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultemulatorinstallcount',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultemulatoruninstallcount',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultemulatoruninstallnextdaycount',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultengineactivity',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultenginedau',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultengineinstall',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultengineuninstallrate',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultgeneralapkinsterror',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultgeneralengineinstall',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultgeneralengineinsterror',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultgeneralenginiterror',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultgeneralosversion',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultgeneraluninstallreason',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultretention',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultretentionengine',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultusercomputerinfocpu',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultusercomputerinfomemory',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
        migrations.AlterField(
            model_name='resultusercomputerinfoos',
            name='channel',
            field=models.CharField(blank=True, default='bscn', max_length=64),
        ),
    ]
