# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0053_auto_20160727_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultappactivity',
            name='op',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resultappinstall',
            name='op',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resultemulatoractivity',
            name='op',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resultemulatorinstall',
            name='op',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resultengineactivity',
            name='op',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='resultengineinstall',
            name='op',
            field=models.CharField(max_length=64),
        ),
    ]
