# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0055_resultapplocaltop500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultapplocaltop500',
            name='package_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
