# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-03 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0057_enginescope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EngineScope',
            new_name='ScopeEngine',
        ),
        migrations.AlterModelTable(
            name='scopeengine',
            table='scope_engine',
        ),
    ]
