# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0058_auto_20160803_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_id', models.IntegerField(default=0)),
                ('result_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('install_success_user', models.IntegerField(default=0)),
                ('install_fail_user', models.IntegerField(default=0)),
                ('download_begin_user', models.IntegerField(default=0)),
                ('download_ok_user', models.IntegerField(default=0)),
                ('init_success_user', models.IntegerField(default=0)),
                ('init_not_success_user', models.IntegerField(default=0)),
                ('init_fail_user', models.IntegerField(default=0)),
                ('first_init_success_user', models.IntegerField(default=0)),
                ('first_init_fail_user', models.IntegerField(default=0)),
                ('update_success_user', models.IntegerField(default=0)),
                ('update_fail_user', models.IntegerField(default=0)),
                ('update_init_success_user', models.IntegerField(default=0)),
                ('update_init_fail_user', models.IntegerField(default=0)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'result_usercomputerinfo_os',
            },
        ),
    ]
