# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0059_enginestats'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enginestats',
            table='stats_engine',
        ),
    ]
