# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0061_scopeemulator'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatorStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_id', models.IntegerField(default=0)),
                ('result_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('install_success_user', models.IntegerField(default=0)),
                ('install_fail_user', models.IntegerField(default=0)),
                ('uninstall_success_user', models.IntegerField(default=0)),
                ('next_day_uninstall_success_user', models.IntegerField(default=0)),
                ('init_success_user', models.IntegerField(default=0)),
                ('init_fail_user', models.IntegerField(default=0)),
                ('init_user', models.IntegerField(default=0)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'stats_emulator',
            },
        ),
    ]
