# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0062_emulatorstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorstats',
            name='next_day_uninstall_success_user_base_on_engine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emulatorstats',
            name='uninstall_success_user_base_on_engine',
            field=models.IntegerField(default=0),
        ),
    ]
