# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0063_auto_20160809_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorstats',
            name='install_and_init_success_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emulatorstats',
            name='retention_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emulatorstats',
            name='retention_7',
            field=models.IntegerField(default=0),
        ),
    ]
