# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0064_auto_20160809_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorstats',
            name='engine_install_and_init_success_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emulatorstats',
            name='retention_2_base_on_engine',
            field=models.IntegerField(default=0),
        ),
    ]
