# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0065_auto_20160809_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorstats',
            name='engine_install_and_init_success_user2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emulatorstats',
            name='retention_2_base_on_engine2',
            field=models.IntegerField(default=0),
        ),
    ]
