# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0066_auto_20160809_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='enginestats',
            name='first_init_no_update_and_next_day_uninstall_emulator_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enginestats',
            name='first_init_no_update_and_uninstall_emulator_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enginestats',
            name='first_init_no_update_success_user',
            field=models.IntegerField(default=0),
        ),
    ]
