# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0070_apptotalstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptotalstat',
            name='daily_install_from_download',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apptotalstat',
            name='daily_install_from_download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apptotalstat',
            name='daily_install_from_download_fail',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apptotalstat',
            name='daily_install_from_download_fail_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
