# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0072_auto_20160810_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPackagenameStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_id', models.PositiveIntegerField(default=0)),
                ('result_date', models.DateField(verbose_name='\u65e5\u671f')),
                ('daily_user_init', models.PositiveIntegerField(default=0)),
                ('daily_user_init_count', models.PositiveIntegerField(default=0)),
                ('daily_init_fail', models.PositiveIntegerField(default=0)),
                ('daily_init_fail_count', models.PositiveIntegerField(default=0)),
                ('daily_install', models.PositiveIntegerField(default=0)),
                ('daily_install_count', models.PositiveIntegerField(default=0)),
                ('daily_install_fail', models.PositiveIntegerField(default=0)),
                ('daily_install_fail_count', models.PositiveIntegerField(default=0)),
                ('daily_download', models.PositiveIntegerField(default=0)),
                ('daily_download_count', models.PositiveIntegerField(default=0)),
                ('daily_download_fail', models.PositiveIntegerField(default=0)),
                ('daily_download_fail_count', models.PositiveIntegerField(default=0)),
                ('daily_install_from_download', models.PositiveIntegerField(default=0)),
                ('daily_install_from_download_count', models.PositiveIntegerField(default=0)),
                ('daily_install_from_download_fail', models.PositiveIntegerField(default=0)),
                ('daily_install_from_download_fail_count', models.PositiveIntegerField(default=0)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'stats_app_package_name',
            },
        ),
        migrations.CreateModel(
            name='ScopeAppPackagename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modes', models.CharField(default='day', max_length=20)),
                ('package_name', models.CharField(blank=True, default='', max_length=255)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'scope_app_package_name',
            },
        ),
    ]
