# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0073_apppackagenamestat_scopeapppackagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorstats',
            name='acc_install_success_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enginestats',
            name='acc_install_success_user',
            field=models.IntegerField(default=0),
        ),
    ]
