# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0074_auto_20160816_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorstats',
            name='init_success_count',
            field=models.IntegerField(default=0),
        ),
    ]
