# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastats', '0075_emulatorstats_init_success_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulatorstats',
            name='retention_14_base_on_engine_normal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emulatorstats',
            name='retention_7_base_on_engine_normal',
            field=models.IntegerField(default=0),
        ),
    ]
