# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppCenterGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('platform_game_ids', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=32, null=True)),
                ('icon_url', models.CharField(max_length=1024, null=True)),
                ('size', models.IntegerField(null=True)),
                ('download_count', models.IntegerField(default=1000)),
                ('screenshots', models.TextField(help_text='\u622a\u56fe\u5730\u5740', max_length=2048, null=True)),
                ('version', models.CharField(max_length=32, null=True)),
                ('tags', models.CharField(max_length=512, null=True)),
                ('level', models.FloatField(default=5.0)),
                ('instruction', models.CharField(max_length=2048, null=True, verbose_name='\u7b80\u4ecb')),
                ('description', models.TextField(help_text='\u63cf\u8ff0', null=True)),
                ('status', models.IntegerField(default=1, verbose_name='\u6e38\u620f\u72b6\u6001 1\u8868\u793a\u6b63\u5e38')),
                ('icon_tag_id', models.IntegerField(null=True, verbose_name='icon_tag')),
                ('small_icon_url', models.CharField(max_length=1024, null=True)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppCenterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_list_id', models.IntegerField(verbose_name='\u6e38\u620f\u63a8\u8350list id')),
                ('app_center_id', models.IntegerField(verbose_name='APP id')),
                ('order', models.IntegerField(default=0, verbose_name='\u6392\u5e8f 0\u6392\u5728\u7b2c\u4e00\u4e2a')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargeReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=128)),
                ('order_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=256)),
                ('game_name', models.CharField(max_length=64, null=True)),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'manage_charge_return',
            },
        ),
        migrations.CreateModel(
            name='GameLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=32, null=True)),
                ('platformId', models.IntegerField()),
                ('platform_game_id', models.IntegerField()),
                ('icon_url', models.CharField(max_length=1024, null=True)),
                ('size', models.IntegerField(null=True)),
                ('download_count', models.IntegerField(default=1000)),
                ('modify_date', models.DateTimeField(verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('screenshots', models.TextField(help_text='\u622a\u56fe\u5730\u5740', max_length=2048, null=True)),
                ('screenshots_type', models.CharField(default='shu', max_length=32)),
                ('version', models.CharField(max_length=32, null=True)),
                ('tags', models.CharField(max_length=512, null=True)),
                ('level', models.IntegerField(default=0, null=True)),
                ('instruction', models.CharField(max_length=2048, null=True)),
                ('description', models.TextField(help_text='\u63cf\u8ff0')),
                ('deleted', models.IntegerField(default=0)),
                ('bs_deleted', models.IntegerField(default=0, null=True)),
                ('download_url', models.CharField(max_length=512, null=True, verbose_name='\u4e0b\u8f7d\u94fe\u63a5')),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('downloadqrcode_url', models.CharField(max_length=512, null=True, verbose_name='\u4e0b\u8f7d\u5730\u5740\u7684\u4e8c\u7ef4\u7801URL')),
                ('package_name', models.CharField(max_length=256, null=True, verbose_name='\u5305\u540d')),
                ('pinyin', models.CharField(max_length=256, null=True, verbose_name='\u62fc\u97f3')),
                ('initails_pinyin', models.CharField(max_length=256, null=True, verbose_name='\u62fc\u97f3\u9996\u5b57\u6bcd')),
            ],
            options={
                'db_table': 'game_library',
            },
        ),
        migrations.CreateModel(
            name='GameLibraryModify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=64, null=True)),
                ('type', models.CharField(max_length=32, null=True)),
                ('icon_url', models.CharField(max_length=1024, null=True)),
                ('size', models.IntegerField(null=True)),
                ('download_count', models.IntegerField(null=True)),
                ('screenshots', models.TextField(help_text='\u622a\u56fe\u5730\u5740', max_length=2048, null=True)),
                ('version', models.CharField(max_length=32, null=True)),
                ('tags', models.CharField(max_length=512, null=True)),
                ('level', models.IntegerField(null=True)),
                ('instruction', models.CharField(max_length=2048, null=True)),
                ('description', models.TextField(help_text='\u63cf\u8ff0', null=True)),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('screenshots_type', models.CharField(default='shu', max_length=32, null=True)),
                ('download_url', models.CharField(max_length=512, null=True, verbose_name='\u4e0b\u8f7d\u94fe\u63a5')),
                ('pinyin', models.CharField(max_length=256, null=True, verbose_name='\u62fc\u97f3')),
                ('initails_pinyin', models.CharField(max_length=256, null=True, verbose_name='\u62fc\u97f3\u9996\u5b57\u6bcd')),
            ],
            options={
                'db_table': 'game_library_modify',
            },
        ),
        migrations.CreateModel(
            name='IconTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('comment', models.CharField(max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OssPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=250, verbose_name='\u6587\u4ef6\u5b58\u50a8\u4f4d\u7f6e')),
                ('status', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('file_type', models.CharField(max_length=20, null=True, verbose_name='\u6587\u4ef6\u7c7b\u578b')),
                ('img_size', models.CharField(help_text='\u683c\u5f0f:80x80', max_length=20, null=True, verbose_name='\u56fe\u7247\u5927\u5c0f')),
                ('bucket', models.CharField(default=b'bst-appcenter', max_length=20, verbose_name='BUCKET')),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
                ('upload_dir', models.CharField(default=b'package', max_length=250, verbose_name='\u6587\u4ef6\u5b58\u50a8\u4f4d\u7f6e')),
                ('type', models.CharField(max_length=50, verbose_name='\u5305\u7c7b\u578b')),
                ('version', models.CharField(max_length=20, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('key', models.CharField(max_length=300, null=True, verbose_name='key')),
                ('md5', models.CharField(max_length=256, null=True, verbose_name='md5')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='RatingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=100, unique=True)),
                ('app_center_id', models.IntegerField(verbose_name='APP center id')),
                ('level', models.FloatField(default=5.0)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2048, null=True)),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u63a8\u8350\u5217\u8868\u540d\u79f0')),
                ('flag', models.CharField(max_length=64, null=True, verbose_name='\u63a8\u8350\u5217\u8868\u82f1\u6587\u540d\u79f0')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(default=1)),
                ('word', models.CharField(blank=True, help_text='\u641c\u7d22\u5173\u952e\u8bcd', max_length=128)),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'manage_search_key_word',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(default='flag', max_length=100, verbose_name='\u4e13\u9898flag')),
                ('topic_name', models.CharField(max_length=100, null=True, verbose_name='\u4e13\u9898\u540d\u79f0')),
                ('big_image_url', models.CharField(max_length=1024, null=True, verbose_name='\u4e13\u9898\u5927\u56fe')),
                ('small_image_url', models.CharField(max_length=1024, null=True, verbose_name='\u4e13\u9898\u5c0f\u56fe')),
                ('url', models.CharField(max_length=1024, null=True, verbose_name='\u4e13\u9898\u7684\u94fe\u63a5')),
                ('order', models.IntegerField(default=0, verbose_name='\u6392\u5e8f 0\u6392\u5728\u7b2c\u4e00\u4e2a')),
                ('status', models.BooleanField(default=True, verbose_name='\u4e13\u9898\u72b6\u6001')),
                ('type', models.CharField(default='zhuanti', max_length=32, verbose_name='lunbo or zhuanti')),
                ('game_libaray_id', models.IntegerField(null=True, verbose_name='\u6e20\u9053\u5305id')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(null=True, verbose_name='topic_id')),
                ('app_center_game_id', models.IntegerField(null=True, verbose_name='app_center_game_id')),
                ('order', models.IntegerField(default=0, verbose_name='\u6392\u5e8f 0\u6392\u5728\u7b2c\u4e00\u4e2a')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Total360Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformId', models.IntegerField()),
                ('platform_game_id', models.IntegerField()),
                ('game_name', models.CharField(help_text='name', max_length=64)),
                ('type', models.CharField(help_text='categoryName', max_length=32, null=True)),
                ('icon_url', models.CharField(help_text='iconUrl', max_length=1024, null=True)),
                ('size', models.IntegerField(help_text='apkSize', null=True)),
                ('download_count', models.IntegerField(default=1000, help_text='downloadTimes')),
                ('modify_date', models.DateTimeField(help_text='updateTime', verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('screenshots', models.TextField(help_text='screenshotsUrl', max_length=2048, null=True)),
                ('screenshots_type', models.CharField(default='shu', max_length=32)),
                ('version', models.CharField(help_text='versionCode', max_length=32, null=True)),
                ('tags', models.CharField(help_text='tag', max_length=512, null=True)),
                ('level', models.FloatField(default=0.0, help_text='rating', null=True)),
                ('instruction', models.CharField(help_text='brief', max_length=2048, null=True)),
                ('description', models.TextField(help_text='\u63cf\u8ff0')),
                ('deleted', models.IntegerField(default=0, help_text='\u622a\u56fe\u5730\u5740')),
                ('download_url', models.CharField(max_length=512, null=True, verbose_name='downloadUrl')),
                ('downloadqrcode_url', models.CharField(max_length=512, null=True, verbose_name='\u4e0b\u8f7d\u5730\u5740\u7684\u4e8c\u7ef4\u7801URL')),
                ('package_name', models.CharField(max_length=256, null=True, verbose_name='packageName')),
                ('apk_md5', models.CharField(help_text='apkMd5', max_length=32, null=True)),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='\u90ae\u7bb1', max_length=100)),
                ('content', models.TextField(help_text='\u53cd\u9988\u5185\u5bb9', max_length=2048)),
                ('type', models.TextField(help_text='\u53cd\u9988\u5185\u5bb9\u7c7b\u578b', max_length=512, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'db_table': 'user_feed_back',
            },
        ),
    ]
