# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total360game',
            name='platform_game_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterModelTable(
            name='total360game',
            table='total_360_game',
        ),
    ]
