# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0002_auto_20160726_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcentergame',
            name='search_weight',
            field=models.IntegerField(null=True, verbose_name='\u641c\u7d22\u6743\u91cd'),
        ),
        migrations.AlterField(
            model_name='total360game',
            name='version',
            field=models.CharField(help_text='versionName', max_length=32, null=True),
        ),
    ]
