# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0005_auto_20160804_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osspackage',
            name='desc',
            field=models.TextField(blank=True, default=b'', verbose_name='\u63cf\u8ff0'),
        ),
    ]
