# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0006_auto_20160804_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='osspackage',
            name='mandatory',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f3a\u5236\u5347\u7ea7'),
        ),
    ]
