# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0008_recommendinstallapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendinstallapp',
            name='game_library_id',
            field=models.IntegerField(unique=True),
        ),
    ]
