# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0009_auto_20160818_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_image_url', models.CharField(max_length=1024, null=True)),
                ('big_image_download_url', models.CharField(max_length=1024, null=True)),
                ('big_image_height', models.CharField(max_length=127, null=True)),
                ('big_image_weight', models.CharField(max_length=127, null=True)),
                ('small_image_url', models.CharField(max_length=1024, null=True)),
                ('exit_button_icon_url', models.CharField(max_length=1024, null=True)),
                ('exit_button_height', models.CharField(max_length=127, null=True)),
                ('exit_button_weight', models.CharField(max_length=127, null=True)),
                ('exit_button_margin_top', models.CharField(max_length=127, null=True)),
                ('exit_button_margin_right', models.CharField(max_length=127, null=True)),
                ('button1_type', models.CharField(default='normal', max_length=127, null=True)),
                ('button1_redirect_url', models.CharField(max_length=1024, null=True)),
                ('button1_icon_url', models.CharField(max_length=1024, null=True)),
                ('button1_download_url', models.CharField(max_length=1024, null=True)),
                ('button1_height', models.CharField(max_length=127, null=True)),
                ('button1_weight', models.CharField(max_length=127, null=True)),
                ('button1_margin_top', models.CharField(max_length=127, null=True)),
                ('button1_margin_left', models.CharField(max_length=127, null=True)),
                ('button2_type', models.CharField(default='normal', max_length=127, null=True)),
                ('button2_redirect_url', models.CharField(max_length=1024, null=True)),
                ('button2_icon_url', models.CharField(max_length=1024, null=True)),
                ('button2_download_url', models.CharField(max_length=1024, null=True)),
                ('button2_height', models.CharField(max_length=127, null=True)),
                ('button2_weight', models.CharField(max_length=127, null=True)),
                ('button2_margin_top', models.CharField(max_length=127, null=True)),
                ('button2_margin_left', models.CharField(max_length=127, null=True)),
                ('button3_type', models.CharField(default='normal', max_length=127, null=True)),
                ('button3_redirect_url', models.CharField(max_length=1024, null=True)),
                ('button3_icon_url', models.CharField(max_length=1024, null=True)),
                ('button3_download_url', models.CharField(max_length=1024, null=True)),
                ('button3_height', models.CharField(max_length=127, null=True)),
                ('button3_weight', models.CharField(max_length=127, null=True)),
                ('button3_margin_top', models.CharField(max_length=127, null=True)),
                ('button3_margin_left', models.CharField(max_length=127, null=True)),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
