# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelibrary',
            name='game_name_lower',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
