# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-31 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0011_gamelibrary_game_name_lower'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreInstallGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=128)),
                ('partner_name_zh', models.CharField(max_length=128, null=True)),
                ('game_name', models.CharField(max_length=128, null=True)),
                ('package_name', models.CharField(max_length=256, verbose_name='\u5305\u540d')),
                ('download_url', models.CharField(max_length=1024, verbose_name='download_url')),
                ('icon_url', models.CharField(max_length=1024, verbose_name='icon_url')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
