# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0008_searchdefaultquery'),
        ('bluestacks', '0011_auto_20160824_1538'),
    ]

    operations = [
    ]
