# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-31 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0012_merge'),
        ('bluestacks', '0012_partnerpreinstallgame'),
    ]

    operations = [
    ]
