# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bluestacks', '0012_partnerpreinstallgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=250, verbose_name='\u6587\u4ef6\u5b58\u50a8\u4f4d\u7f6e')),
                ('status', models.BooleanField(default=True, verbose_name='\u72b6\u6001')),
                ('bucket', models.CharField(default=b'bst-appcenter', max_length=20, verbose_name='BUCKET')),
                ('type', models.CharField(max_length=50, verbose_name='\u5305\u7c7b\u578b')),
                ('version', models.CharField(max_length=20, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('md5', models.CharField(max_length=256, null=True, verbose_name='md5')),
                ('desc', models.TextField(blank=True, default=b'', verbose_name='\u63cf\u8ff0')),
                ('mandatory', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5f3a\u5236\u5347\u7ea7')),
                ('uptime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u6570\u636e\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
