CFLAGS = $(CFLAGS) /nologo /W4 /WX
CFLAGS = $(CFLAGS) /I$(S)
CFLAGS = $(CFLAGS) /I$(DDKDIR)\inc
CFLAGS = $(CFLAGS) /I$(DDKDIR)\inc\api
CFLAGS = $(CFLAGS) /I$(DDKDIR)\inc\ddk
CFLAGS = $(CFLAGS) /I$(DDKDIR)\inc\crt

CFLAGS = $(CFLAGS) /DSTD_CALL /DCONDITION_HANDLING=1
CFLAGS = $(CFLAGS) /DNT_INST=0 /DWIN32=100 /D_NT1X_=100 /DWINNT=1
CFLAGS = $(CFLAGS) /D_WIN32_IE=0x0800
CFLAGS = $(CFLAGS) /DWIN32_LEAN_AND_MEAN=1 /DDEVL=1 /D__BUILDMACHINE__=WinDDK
CFLAGS = $(CFLAGS) /DFPO=0 /DNDEBUG /D_DLL=1

CFLAGS = $(CFLAGS) /Zc:wchar_t- /Zl /Zp8 /Gy /Gm- -cbstring /Gz
CFLAGS = $(CFLAGS) /EHs-c- /GR- /GF /GS /Zi /Oi /Oy- /typedil-

CFLAGS = $(CFLAGS) /DKMDF_MAJOR_VERSION=1
CFLAGS = $(CFLAGS) /DKMDF_MINOR_VERSION=9
CFLAGS = $(CFLAGS) /DKMDF_MAJOR_VERSION_STRING=01
CFLAGS = $(CFLAGS) /DKMDF_MINOR_VERSION_STRING=009

CFLAGS = $(CFLAGS) /wd4018
CFLAGS = $(CFLAGS) /wd4055
CFLAGS = $(CFLAGS) /wd4100
CFLAGS = $(CFLAGS) /wd4127
CFLAGS = $(CFLAGS) /wd4200
CFLAGS = $(CFLAGS) /wd4201

CFLAGS = $(CFLAGS) /FI$(DDKDIR)\inc\api\warning.h

CFLAGS = $(CFLAGS) /DKERNEL_MODE

LDFLAGS = $(LDFLAGS) /debug

ASFLAGS = $(ASFLAGS) /nologo
ASFLAGS = $(ASFLAGS) /I$(S)\include

RCFLAGS = $(RCFLAGS) /i$(DDKDIR)\inc\api
RCFLAGS = $(RCFLAGS) /i$(S)

RCFLAGS = $(RCFLAGS) /dVERSION_MAJOR=$(VERSION_MAJOR)
RCFLAGS = $(RCFLAGS) /dVERSION_MINOR=$(VERSION_MINOR)
RCFLAGS = $(RCFLAGS) /dVERSION_PATCH=$(VERSION_PATCH)
RCFLAGS = $(RCFLAGS) /dVERSION_BUILD=$(VERSION_BUILD)

!IF "$(BUILD_TYPE)" == "DBG"
CFLAGS  = $(CFLAGS) /Od /D_DEBUG
!ELSE
CFLAGS = $(CFLAGS) /Oxt /DNDEBUG
!ENDIF

!IF "$(TARGET_ARCH)" == "amd64"
CFLAGS = $(CFLAGS) /D_WIN64 /D_AMD64_=1 /DAMD64
CFLAGS = $(CFLAGS) /D_WIN32_WINNT=0x0502 /DWINVER=0x0502 
CFLAGS = $(CFLAGS) /DNTDDI_VERSION=0x05020200
!ELSE
CFLAGS = $(CFLAGS) /D_X86_=1 /Di386=1
CFLAGS = $(CFLAGS) /hotpatch
CFLAGS = $(CFLAGS) /D_WIN32_WINNT=0x0501 /DWINVER=0x0501 
CFLAGS = $(CFLAGS) /DNTDDI_VERSION=0x05010300
!ENDIF

###

AS32 = %DDKDIR%\bin\x86\ml.exe
AS64 = %DDKDIR%\bin\x86\amd64\ml64.exe

!IF "$(TARGET_ARCH)" == "amd64"
CC = %DDKDIR%\bin\x86\amd64\cl.exe
LD = %DDKDIR%\bin\x86\amd64\link.exe
AS = $(AS64)
!ELSE
CC = %DDKDIR%\bin\x86\x86\cl.exe
LD = %DDKDIR%\bin\x86\x86\link.exe
AS = $(AS32)
!ENDIF

RC = %DDKDIR%\bin\x86\rc.exe

SIGNTOOL = $(DDKDIR)\bin\x86\SignTool.exe

OBJS = $(OBJS) $(SRCS:.c=.obj) $(ASMS:.asm=.obj)

!IFDEF BUILD_HYBRID
CFLAGS  = $(CFLAGS) /DBUILD_HYBRID
!ENDIF

.SUFFIXES: .c .obj

.c.obj:
	$(CC) $(CFLAGS) /c /Fo$@ $<

.asm.obj:
	$(AS) $(ASFLAGS) /c /Fo$@ $<

.rc.res:
	$(RC) $(RCFLAGS) /fo$@ $<
