PROG = HD-VMCommand
SRCS = \
    $(SUL)\Version.cs \
    $(SUL)\Common\DotNet\Strings.cs \
    $(SUL)\Common\DotNet\User.cs \
    $(SUL)\Common\DotNet\Logger.cs \
    $(SUL)\Common\DotNet\MonitorLocator.cs \
    Command.cs \
    ConsoleControl.cs \
    Tool.cs \
    AssemblyInfo.cs

CSFLAGS = $(CSFLAGS) /debug:full
CSFLAGS = $(CSFLAGS) /platform:x86

!INCLUDE $(M)\win_csharp.mk
