all:
	msbuild $(SUL)\Gamemanager\Dotnet\VSSolution\BluestacksGameManager\BluestacksGameManager\BluestacksGameManager.csproj /p:Configuration=Release /p:Platform=x86

clean:
	del /f $(SUL)\Gamemanager\Dotnet\BlueStacks.exe
	del /f $(SUL)\Gamemanager\Dotnet\BlueStacks.pdb
